apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-automated-deployments
  labels:
    app: demo-automated-deployments
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-automated-deployments
  template:
    metadata:
      labels:
        app: demo-automated-deployments
    spec:
      containers:
        - name: demo-automated-deployments
          image: aksdemotestdeployments.azurecr.io/image-workflow-1715778238152:latest
          ports:
            - containerPort: 8000