apiVersion: v1
kind: Service
metadata:
  name: demo-automated-deployments
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: demo-automated-deployments
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000